---
output:
  pdf_document: default
  html_document: default
---

## Multiple Regression
```{r}
##Simulation1
library(ggplot2)
data <-read.csv("C://Users//Cahil//PycharmProjects//ThesisNetwork//DataSets//Sim1Results4effectedlowerhighernob13.csv",header = TRUE)
ao7 <- aov(Mortality~A+B,data = data)
summary(ao7)
dataA <-subset(data, B == 0.5)
ao8 <- aov(Mortality~A,data = dataA)
summary(ao8)
dataB <- subset(data, A == 0.1)
ao9 <- aov(Mortality~B,data = dataB)
summary(ao9)
ggplot(data = data, aes(x=as.factor(B), y=Mortality)) + 
  geom_boxplot()

ggplot(data = data, aes(x=as.factor(A), y=Mortality)) + 
  geom_boxplot()
ggplot(data = data, aes(x=Mortality)) + 
  geom_histogram()+facet_grid(vars(A),vars(B))+xlab("A Values")+ylab("B Values")+ggtitle("Values of A on x axis and Values of B on Y axis")


a <- subset(data, A==0.1 & B ==0.5)
a2 <- subset(data, A==0.5 & B ==0.5)
a3 <- subset(data, A==0.9 & B ==0.5)
b3 <- subset(data, B==0.9 & A == 0.1)
b2 <- subset(data, B==0.5 & A == 0.1)
b <- subset(data, B==0.1 & A == 0.1)
mean(a$Mortality)
mean(a2$Mortality)
mean(a3$Mortality)
mean(b$Mortality)
mean(b2$Mortality)
mean(b3$Mortality)


```

```{r}
#Simulation 2
data <-read.csv("C://Users//Cahil//PycharmProjects//ThesisNetwork//DataSets//Sim1Results42.csv",header = TRUE)
ao1 <- aov(Mortality~A+B,data = data)
summary(ao1)
dataA <-subset(data, B == 0.5)
ao2 <- aov(Mortality~A,data = dataA)
summary(ao2)
dataB <- subset(data, A == 0.1)
ao3 <- aov(Mortality~B,data = dataB)
summary(ao3)
ggplot(data = data, aes(x=as.factor(B), y=Mortality)) + 
  geom_boxplot()

ggplot(data = data, aes(x=as.factor(A), y=Mortality)) + 
  geom_boxplot()

ggplot(data = data, aes(x=Mortality)) + 
  geom_histogram()+facet_grid(vars(A),vars(B))+xlab("A Values")+ylab("B Values")+ggtitle("Values of A on x axis and Values of B on Y axis")


a <- subset(data, A==0.1 & B ==0.5)
a2 <- subset(data, A==0.5 & B ==0.5)
a3 <- subset(data, A==0.9 & B ==0.5)
b3 <- subset(data, B==0.9 & A == 0.1)
b2 <- subset(data, B==0.5 & A == 0.1)
b <- subset(data, B==0.1 & A == 0.1)
mean(a$Mortality)
mean(a2$Mortality)
mean(a3$Mortality)
mean(b$Mortality)
mean(b2$Mortality)
mean(b3$Mortality)

```
```{r}
#Simulation 3
data <-read.csv("C://Users//Cahil//PycharmProjects//ThesisNetwork//DataSets//Sim1Results10.csv",header = TRUE)
ao10 <- aov(NumAffected~A+B,data = data)
summary(ao10)
dataA <-subset(data, B == 0.5)
ao11 <- aov(NumAffected~A,data = dataA)
summary(ao11)
dataB <- subset(data, A == 0.1)
ao12 <- aov(NumAffected~B,data = dataB)
summary(ao12)
ggplot(data = data, aes(x=as.factor(B), y=Mortality)) + 
  geom_boxplot()

ggplot(data = data, aes(x=as.factor(A), y=Mortality)) + 
  geom_boxplot()

ggplot(data = data, aes(x=Mortality)) + 
  geom_histogram()+facet_grid(vars(A),vars(B))+xlab("A Values")+ylab("B Values")+ggtitle("Values of A on x axis and Values of B on Y axis")


a <- subset(data, A==0.1 & B ==0.5)
a2 <- subset(data, A==0.5 & B ==0.5)
a3 <- subset(data, A==0.9 & B ==0.5)
b3 <- subset(data, B==0.9 & A == 0.1)
b2 <- subset(data, B==0.5 & A == 0.1)
b <- subset(data, B==0.1 & A == 0.1)
mean(a$NumAffected)
mean(a2$NumAffected)
mean(a3$NumAffected)
mean(b$NumAffected)
mean(b2$NumAffected)
mean(b3$NumAffected)
mean(a$Mortality)
mean(a2$Mortality)
mean(a3$Mortality)
mean(b$Mortality)
mean(b2$Mortality)
mean(b3$Mortality)

```